// frontend/src/components/common/ErrorBoundary.vue
<template>
  <div v-if="hasError" class="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center p-4">
    <div class="max-w-md w-full">
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-red-200 dark:border-red-800 p-6">
        <div class="flex items-center space-x-3 mb-4">
          <ExclamationTriangleIcon class="h-8 w-8 text-red-500" />
          <div>
            <h1 class="text-lg font-semibold text-gray-900 dark:text-white">Something went wrong</h1>
            <p class="text-sm text-gray-600 dark:text-gray-400">An unexpected error occurred</p>
          </div>
        </div>
        
        <div v-if="error && showDetails" class="mb-4 p-3 bg-gray-50 dark:bg-gray-700 rounded-md">
          <p class="text-xs font-mono text-gray-700 dark:text-gray-300 break-all">
            {{ error.message || error.toString() }}
          </p>
        </div>
        
        <div class="flex flex-col sm:flex-row gap-3">
          <button
            @click="retry"
            class="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors"
          >
            Try Again
          </button>
          <button
            @click="goHome"
            class="flex-1 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-900 dark:text-gray-100 px-4 py-2 rounded-md text-sm font-medium transition-colors"
          >
            Go to Dashboard
          </button>
        </div>
        
        <button
          @click="showDetails = !showDetails"
          class="w-full mt-3 text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300"
        >
          {{ showDetails ? 'Hide' : 'Show' }} Error Details
        </button>
      </div>
    </div>
  </div>
  <slot v-else />
</template>

<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue'
import { useRouter } from 'vue-router'
import { ExclamationTriangleIcon } from '@heroicons/vue/24/outline'

const router = useRouter()

const hasError = ref(false)
const error = ref<Error | null>(null)
const showDetails = ref(false)

const retry = () => {
  hasError.value = false
  error.value = null
  showDetails.value = false
  // Force component re-render
  window.location.reload()
}

const goHome = () => {
  hasError.value = false
  error.value = null
  showDetails.value = false
  router.push('/dashboard')
}

onErrorCaptured((err: Error) => {
  console.error('Error caught by boundary:', err)
  hasError.value = true
  error.value = err
  return false // Prevent error from propagating
})
</script>

// frontend/src/components/ErrorBoundary.jsx
import { Component } from 'react'

class ErrorBoundary extends Component {
  constructor(props) {
    super(props)
    this.state = { hasError: false, error: null }
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error }
  }

  componentDidCatch(error, errorInfo) {
    console.error('Error caught by boundary:', error, errorInfo)
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
          <div className="max-w-md w-full bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6">
            <div className="text-center">
              <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-red-100 dark:bg-red-900">
                <svg
                  className="h-6 w-6 text-red-600 dark:text-red-400"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.732-.833-2.464 0L4.35 16.5c-.77.833.192 2.5 1.732 2.5z"
                  />
                </svg>
              </div>
              <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">
                Something went wrong
              </h3>
              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                An unexpected error occurred. Please refresh the page and try again.
              </p>
              <div className="mt-6">
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={() => window.location.reload()}
                >
                  Refresh Page
                </button>
              </div>
            </div>
          </div>
        </div>
      )
    }

    return this.props.children
  }
}

export default ErrorBoundary
